### ISSUE TITLE
FDC1's inability to handle JPEG format pictures

### ISSUE THREAD

**Issue by FeathersRe** [FeathersRe/PIXIE#5]
The FDC1 program module crashes when it has a input image of JPG/JPEG format. The following is an example of the output error.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "f:\MS2.PIXIE\Main.py", line 86, in confirm
    first_degree_interface(self.root, image_path, output_path)
  File "f:\MS2.PIXIE\First_degree.py", line 19, in __init__
    self.filename = ttk.PhotoImage(file=self.path)
  File "C:\Python\lib\tkinter\__init__.py", line 4093, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python\lib\tkinter\__init__.py", line 4038, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "F:\MS2.PIXIE\Inputs\1.jpg"`

**Comment by FeathersRe** [comment]
This is likely caused by Tkinter's unreliable PhotoImage function which would sometimes inadvertently crash when trying to open image inputs of formats other than the ".png".

Solution:
Changes has been made to the _First_degree.py_ script, where instead of using `ttk.PhotoImage(file=self.path)` to call for the image inputs, `ImageTk.PhotoImage(file= self.path)` from Python's Pillow Lib is used instead to ensure consistency.
